# Generated by Django 5.0.7 on 2024-07-19 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dName", models.CharField(max_length=255, verbose_name="DeptName")),
                ("HOD", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="member",
            name="fname",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eName", models.CharField(max_length=255)),
                (
                    "deptID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.dept"
                    ),
                ),
            ],
        ),
    ]
