# Generated by Django 5.0.7 on 2024-07-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_dept_alter_member_fname_emp"),
    ]

    operations = [
        migrations.AddField(
            model_name="emp",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=1
            ),
        ),
    ]
