# Generated by Django 5.0.7 on 2024-08-05 09:38

import django_enum_choices.choice_builders
import django_enum_choices.fields
import user.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_master_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="emp",
            name="relation",
            field=django_enum_choices.fields.EnumChoiceField(
                choice_builder=django_enum_choices.choice_builders.value_value,
                choices=[
                    ("Self", "Self"),
                    ("Spouse", "Spouse"),
                    ("Parent", "Parent"),
                    ("Child", "Child"),
                ],
                default=user.models.RelationsEnum["SELF"],
                enum_class=user.models.RelationsEnum,
                max_length=6,
            ),
        ),
    ]
