# Generated by Django 5.0.7 on 2024-08-05 09:50

import django_mysql.models
import user.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_emp_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emp",
            name="relation",
            field=django_mysql.models.EnumField(
                choices=[
                    (user.models.RelationsEnum["SELF"], "Self"),
                    (user.models.RelationsEnum["SPOUSE"], "Spouse"),
                    (user.models.RelationsEnum["PARENT"], "Parent"),
                    (user.models.RelationsEnum["CHILD"], "Child"),
                ],
                default=user.models.RelationsEnum["SELF"],
            ),
        ),
    ]
