# Generated by Django 5.0.7 on 2024-08-05 09:55

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_emp_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emp",
            name="relation",
            field=django_mysql.models.EnumField(
                choices=[
                    ("Self", "SELF"),
                    ("Spouse", "SPOUSE"),
                    ("Parent", "PARENT"),
                    ("Child", "CHILD"),
                ],
                default="Self",
            ),
        ),
    ]
