# Generated by Django 5.0.7 on 2024-08-05 10:05

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_emp_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emp",
            name="relation",
            field=django_mysql.models.EnumField(
                choices=[
                    ("Self", "Self"),
                    ("Spouse", "Spouse"),
                    ("Parent", "Parent"),
                    ("Child", "Child"),
                ],
                default="Self",
            ),
        ),
    ]
